/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import interfaces.manageInterfaces.ManagePanel;
import business.Car;
import business.CarCatalog;
import interfaces.orderInterfaces.OrderPanel;
import java.awt.CardLayout;

/**
 *
 * @author Brickea
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private CarCatalog carCatalog = new CarCatalog();

    private void initCars() {
        Car c = new Car();
        c.setCarSeriesNumber(1);
        c.setCarCity("Boston");
        c.setCarManufacturers("Toyota");
        c.setCarManufacturedYear(2014);
        c.setCarModelNumber("SE-2");
        c.setCarPposition(1, 2);
        c.setCarCertification(true);
        c.setCarSets(3);
        this.carCatalog.addCar(c);
        c = new Car();
        c.setCarSeriesNumber(2);
        c.setCarCity("New York");
        c.setCarManufacturers("Toyota");
        c.setCarManufacturedYear(2016);
        c.setCarModelNumber("SE-2");
        c.setCarPposition(2, 2);
        c.setCarCertification(true);
        c.setCarSets(2);
        this.carCatalog.addCar(c);
        c = new Car();
        c.setCarSeriesNumber(3);
        c.setCarCity("New York");
        c.setCarManufacturers("GM");
        c.setCarManufacturedYear(2016);
        c.setCarModelNumber("SE-3");
        c.setCarPposition(4, 4);
        c.setCarCertification(false);
        c.setCarSets(2);
        this.carCatalog.addCar(c);
        c = new Car();
        c.setCarSeriesNumber(4);
        c.setCarCity("Boston");
        c.setCarManufacturers("GM");
        c.setCarManufacturedYear(2016);
        c.setCarModelNumber("SE-6");
        c.setCarPposition(2, 2);
        c.setCarCertification(false);
        c.setCarSets(3);
        this.carCatalog.addCar(c);
    }

    public MainFrame() {
        initComponents();
        this.manageBtn.setEnabled(true);
        this.orderBtn.setEnabled(true);
    }

    public void enableManageBtn() {
        this.manageBtn.setEnabled(true);
        this.orderBtn.setEnabled(true);
    }

    public void disableManageBtn() {
        this.manageBtn.setEnabled(false);
        this.orderBtn.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        controlPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        manageBtn = new javax.swing.JButton();
        orderBtn = new javax.swing.JButton();
        viewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jLabel5.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
        jLabel5.setText("Welcome to Uber!");

        manageBtn.setText("Manage cars");
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        orderBtn.setText("Order cars");
        orderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanel4Layout = new javax.swing.GroupLayout(controlPanel4);
        controlPanel4.setLayout(controlPanel4Layout);
        controlPanel4Layout.setHorizontalGroup(
            controlPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(173, 173, 173))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, controlPanel4Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        controlPanel4Layout.setVerticalGroup(
            controlPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(controlPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(orderBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(controlPanel4);

        viewPanel.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(viewPanel);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.disableManageBtn();
        OrderPanel p = new OrderPanel(this.viewPanel, this.carCatalog, this);
        this.viewPanel.add("orderPanel", p);
        CardLayout layout = (CardLayout) this.viewPanel.getLayout();
        layout.next(this.viewPanel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.disableManageBtn();
        ManagePanel p = new ManagePanel(this.viewPanel, this.carCatalog, this);
        this.viewPanel.add("managePanel", p);
        CardLayout layout = (CardLayout) this.viewPanel.getLayout();
        layout.next(this.viewPanel);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                // new MainFrame().setVisible(true);
                MainFrame main = new MainFrame();
                main.setVisible(true);
                main.initCars();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlPanel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton manageBtn;
    private javax.swing.JButton orderBtn;
    private javax.swing.JPanel viewPanel;
    // End of variables declaration//GEN-END:variables
}
