/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces.manageInterfaces;

import business.Car;
import business.CarCatalog;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Brickea
 */
public class SearchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchPanel
     */
    private JPanel viewPanel;
    private CarCatalog carCatalog;
    private Car car;

    public SearchPanel() {
        initComponents();
    }

    public SearchPanel(JPanel viewPanel, Car car, CarCatalog carCatalog) {
        initComponents();
        this.viewPanel = viewPanel;
        this.car = car;
        this.carCatalog = carCatalog;
        this.enableAllInput(false);
        this.showData();
    }

    private void enableAllInput(boolean enable) {
        this.saveCarBtn.setEnabled(enable);
        this.updateBtn.setEnabled(!enable);

        this.carCertificationText.setEnabled(enable);
        this.carCityText.setEnabled(enable);
        this.carManufacturedYearText.setEnabled(enable);
        this.carManufacturersText.setEnabled(enable);
        this.carMudleNumberText.setEnabled(enable);
        this.carPpositionText1Y.setEnabled(enable);
        this.carPpositionTextX.setEnabled(enable);
        this.carSeriesNumberText.setEnabled(enable);
        this.carSetsText.setEnabled(enable);
    }
    
    private void showData(){
        if(this.car.isCarCertification()){
            this.carCertificationText.setSelectedIndex(0);
        }else{
            this.carCertificationText.setSelectedIndex(1);
        }
        
        this.carCityText.setSelectedItem(this.car.getCarCity());
        this.carManufacturedYearText.setText(String.valueOf(this.car.getCarManufacturedYear()));
        this.carManufacturersText.setText(this.car.getCarManufacturers());
        this.carMudleNumberText.setText(this.car.getCarModelNumber());
        this.carPpositionText1Y.setText(String.valueOf(this.car.getCarPposition()[1]));
        this.carPpositionTextX.setText(String.valueOf(this.car.getCarPposition()[0]));
        this.carSeriesNumberText.setText(String.valueOf(this.car.getCarSeriesNumber()));
        this.carSetsText.setText(String.valueOf(this.car.getCarSets()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        carSetsText = new javax.swing.JTextField();
        seriesNumberText7 = new javax.swing.JLabel();
        seriesNumberText2 = new javax.swing.JLabel();
        carManufacturersText = new javax.swing.JTextField();
        carPpositionText1Y = new javax.swing.JTextField();
        seriesNumberText3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        carCertificationText = new javax.swing.JComboBox<>();
        carMudleNumberText = new javax.swing.JTextField();
        saveCarBtn = new javax.swing.JButton();
        seriesNumberText4 = new javax.swing.JLabel();
        carManufacturedYearText = new javax.swing.JTextField();
        carCityText = new javax.swing.JComboBox<>();
        seriesNumberText5 = new javax.swing.JLabel();
        seriesNumberLabel = new javax.swing.JLabel();
        carSeriesNumberText = new javax.swing.JTextField();
        seriesNumberText6 = new javax.swing.JLabel();
        seriesNumberText1 = new javax.swing.JLabel();
        carPpositionTextX = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("宋体", 1, 18)); // NOI18N
        jLabel1.setText("Car Detial");

        seriesNumberText7.setText("Certification");

        seriesNumberText2.setText("Manufacturers");

        seriesNumberText3.setText("Model Number");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        carCertificationText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Not Expired", "Expired" }));

        saveCarBtn.setText("Save");
        saveCarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveCarBtnActionPerformed(evt);
            }
        });

        seriesNumberText4.setText("Manufactured Year");

        carCityText.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Boston", "New York" }));

        seriesNumberText5.setText("City");

        seriesNumberLabel.setText("Series Number");

        seriesNumberText6.setText("Pposition");

        seriesNumberText1.setText("Car Sets");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seriesNumberText7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carCertificationText, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seriesNumberText6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carPpositionTextX, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(carPpositionText1Y, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seriesNumberText5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seriesNumberText4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carManufacturedYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seriesNumberText3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carMudleNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seriesNumberText2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carManufacturersText, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seriesNumberText1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carSetsText, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(seriesNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(carSeriesNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(saveCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriesNumberLabel)
                    .addComponent(carSeriesNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriesNumberText1)
                    .addComponent(carSetsText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriesNumberText2)
                    .addComponent(carManufacturersText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriesNumberText3)
                    .addComponent(carMudleNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriesNumberText4)
                    .addComponent(carManufacturedYearText, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carCityText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seriesNumberText5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seriesNumberText6)
                    .addComponent(carPpositionTextX, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carPpositionText1Y, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seriesNumberText7)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveCarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(carCertificationText, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(460, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.viewPanel.remove(this);
        CardLayout layout = (CardLayout) this.viewPanel.getLayout();
        layout.previous(this.viewPanel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void saveCarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveCarBtnActionPerformed
        // TODO add your handling code here:
        try {
            if (!this.carSeriesNumberText.getText().equals("")) {
                Car testCar = new Car();
                testCar.setCarSeriesNumber(Integer.parseInt(this.carSeriesNumberText.getText()));

                if (((String) this.carCertificationText.getSelectedItem()).equals("Expired")) {
                    testCar.setCarCertification(false);
                } else {
                    testCar.setCarCertification(true);
                }

                testCar.setCarCity((String) this.carCityText.getSelectedItem());
                testCar.setCarManufacturedYear(Integer.parseInt(this.carManufacturedYearText.getText()));
                testCar.setCarManufacturers(this.carManufacturersText.getText());
                testCar.setCarModelNumber(this.carMudleNumberText.getText());
                testCar.setCarPposition(Integer.parseInt(this.carPpositionTextX.getText()), Integer.parseInt(this.carPpositionText1Y.getText()));
                testCar.setCarSets(Integer.parseInt(this.carSetsText.getText()));
                
                CarCatalog testCatalog = new CarCatalog();
                for(Car c : this.carCatalog.getCarCatalog()){
                    testCatalog.addCar(c);
                }
                testCatalog.deleteCar(testCatalog.searchCar(this.car.getCarSeriesNumber()));
                
                if (!testCatalog.isExistCar(testCar)) {
                    this.car.setCarSeriesNumber(Integer.parseInt(this.carSeriesNumberText.getText()));

                    if (((String) this.carCertificationText.getSelectedItem()).equals("Expired")) {
                        this.car.setCarCertification(false);
                    } else {
                        this.car.setCarCertification(true);
                    }

                    this.car.setCarCity((String) this.carCityText.getSelectedItem());
                    this.car.setCarManufacturedYear(Integer.parseInt(this.carManufacturedYearText.getText()));
                    this.car.setCarManufacturers(this.carManufacturersText.getText());
                    this.car.setCarModelNumber(this.carMudleNumberText.getText());
                    this.car.setCarPposition(Integer.parseInt(this.carPpositionTextX.getText()), Integer.parseInt(this.carPpositionText1Y.getText()));
                    this.car.setCarSets(Integer.parseInt(this.carSetsText.getText()));

                    this.enableAllInput(false);
                    this.carCatalog.updateLastTime();
                }else{
                    JOptionPane.showMessageDialog(null, "The series number is exist!");
                }

            } else {
                JOptionPane.showMessageDialog(null, "The series number is empty!");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Please input a valid number!");
        }
    }//GEN-LAST:event_saveCarBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        this.enableAllInput(true);
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> carCertificationText;
    private javax.swing.JComboBox<String> carCityText;
    private javax.swing.JTextField carManufacturedYearText;
    private javax.swing.JTextField carManufacturersText;
    private javax.swing.JTextField carMudleNumberText;
    private javax.swing.JTextField carPpositionText1Y;
    private javax.swing.JTextField carPpositionTextX;
    private javax.swing.JTextField carSeriesNumberText;
    private javax.swing.JTextField carSetsText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton saveCarBtn;
    private javax.swing.JLabel seriesNumberLabel;
    private javax.swing.JLabel seriesNumberText1;
    private javax.swing.JLabel seriesNumberText2;
    private javax.swing.JLabel seriesNumberText3;
    private javax.swing.JLabel seriesNumberText4;
    private javax.swing.JLabel seriesNumberText5;
    private javax.swing.JLabel seriesNumberText6;
    private javax.swing.JLabel seriesNumberText7;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
