-- MySQL Script generated by MySQL Workbench
-- Wed Mar 25 20:36:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`device` (
  `iddevice` INT NOT NULL,
  `deviceTpye` VARCHAR(45) NOT NULL,
  `isconnected` TINYINT NOT NULL,
  PRIMARY KEY (`iddevice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`building`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`building` (
  `idbuilding` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`idbuilding`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`floor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`floor` (
  `idfloor` INT NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `idbuilding` INT NOT NULL,
  PRIMARY KEY (`idfloor`),
  INDEX `idbuilding_idx` (`idbuilding` ASC),
  CONSTRAINT `idbuilding`
    FOREIGN KEY (`idbuilding`)
    REFERENCES `mydb`.`building` (`idbuilding`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`floorMap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`floorMap` (
  `idpoint` INT NOT NULL,
  `x` DECIMAL(45) NOT NULL,
  `y` DECIMAL(45) NOT NULL,
  `pointTpye` VARCHAR(45) NOT NULL DEFAULT 'Indicate what it is, like room, stair, etc',
  `idfloor` INT NOT NULL,
  PRIMARY KEY (`idpoint`),
  INDEX `idFloor_idx` (`idfloor` ASC),
  CONSTRAINT `idFloor`
    FOREIGN KEY (`idfloor`)
    REFERENCES `mydb`.`floor` (`idfloor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`location` (
  `idlocation` INT NOT NULL,
  `idfloor` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `idpoint` INT NOT NULL,
  PRIMARY KEY (`idlocation`),
  INDEX `coordinatePoint_idx` (`idpoint` ASC),
  CONSTRAINT `coordinatePoint`
    FOREIGN KEY (`idpoint`)
    REFERENCES `mydb`.`floorMap` (`idpoint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`position` (
  `idposition` INT NOT NULL,
  `x` DECIMAL(45) NOT NULL,
  `y` DECIMAL(45) NOT NULL,
  `fidfloor` INT NOT NULL,
  `iddevice` INT NOT NULL,
  PRIMARY KEY (`idposition`),
  INDEX `idfloor_idx` (`fidfloor` ASC),
  INDEX `iddevice_idx` (`iddevice` ASC),
  CONSTRAINT `fidfloor`
    FOREIGN KEY (`fidfloor`)
    REFERENCES `mydb`.`floor` (`idfloor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `iddevice`
    FOREIGN KEY (`iddevice`)
    REFERENCES `mydb`.`device` (`iddevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`checkPoint`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`checkPoint` (
  `idcheckingPoint` INT NOT NULL,
  `idposition` INT NOT NULL,
  `idpoint` INT NOT NULL,
  `mode` VARCHAR(45) NOT NULL,
  `idPath` INT NULL,
  PRIMARY KEY (`idcheckingPoint`),
  INDEX `targetLocation_idx` (`idpoint` ASC),
  INDEX `sourceLocation_idx` (`idposition` ASC),
  CONSTRAINT `sourceLocation`
    FOREIGN KEY (`idposition`)
    REFERENCES `mydb`.`position` (`idposition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `targetLocation`
    FOREIGN KEY (`idpoint`)
    REFERENCES `mydb`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`navigationRequest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`navigationRequest` (
  `idnavigationRequest` INT NOT NULL,
  `idposition` INT NOT NULL,
  `idlocation` INT NOT NULL,
  `ifDifferentFloor` INT NOT NULL,
  `checkPoint` INT NULL,
  `mode` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idnavigationRequest`),
  INDEX `targetLocation_idx` (`idlocation` ASC),
  INDEX `checkingPoint_idx` (`checkPoint` ASC),
  INDEX `sourceLocation_idx` (`idposition` ASC),
  CONSTRAINT `UserTargetLocation`
    FOREIGN KEY (`idlocation`)
    REFERENCES `mydb`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `checkingPoint`
    FOREIGN KEY (`checkPoint`)
    REFERENCES `mydb`.`checkPoint` (`idcheckingPoint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UserSourceLocation`
    FOREIGN KEY (`idposition`)
    REFERENCES `mydb`.`position` (`idposition`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`paths` (
  `idpaths` INT NOT NULL,
  `idnavigationRequest` INT NOT NULL,
  PRIMARY KEY (`idpaths`),
  INDEX `idnavigationRequestforPath_idx` (`idnavigationRequest` ASC),
  CONSTRAINT `idnavigationRequestforPath`
    FOREIGN KEY (`idnavigationRequest`)
    REFERENCES `mydb`.`navigationRequest` (`idnavigationRequest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`path`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`path` (
  `idPoints` INT NOT NULL,
  `x` DECIMAL(45) NOT NULL,
  `y` DECIMAL(45) NOT NULL,
  `idpaths` INT NOT NULL,
  PRIMARY KEY (`idPoints`),
  INDEX `idpaths_idx` (`idpaths` ASC),
  CONSTRAINT `idPaths`
    FOREIGN KEY (`idpaths`)
    REFERENCES `mydb`.`paths` (`idpaths`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bluetoothBeacon(real-time udpate)`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bluetoothBeacon(real-time udpate)` (
  `idbluetoothBeacon` INT NOT NULL,
  `idlocation` INT NOT NULL,
  PRIMARY KEY (`idbluetoothBeacon`),
  INDEX `idlocationforBeacon_idx` (`idlocation` ASC),
  CONSTRAINT `idlocationforBeacon`
    FOREIGN KEY (`idlocation`)
    REFERENCES `mydb`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requestComplete`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requestComplete` (
  `idrequestComplete` INT NOT NULL,
  `idnavigationRequest` INT NOT NULL,
  `ifComplete` TINYINT NOT NULL,
  PRIMARY KEY (`idrequestComplete`),
  INDEX `idNavigationRequest_idx` (`idnavigationRequest` ASC),
  CONSTRAINT `UserIdNavigationRequest`
    FOREIGN KEY (`idnavigationRequest`)
    REFERENCES `mydb`.`navigationRequest` (`idnavigationRequest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`originalFloorMap`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`originalFloorMap` (
  `idoriginalFloorMap` INT NOT NULL,
  `excelMap` BLOB NULL,
  `idbuilding` INT NOT NULL,
  `idfloor` INT NOT NULL,
  PRIMARY KEY (`idoriginalFloorMap`),
  INDEX `idBuilding_idx` (`idbuilding` ASC),
  INDEX `idFloor_idx` (`idfloor` ASC),
  CONSTRAINT `OriginalIdBuilding`
    FOREIGN KEY (`idbuilding`)
    REFERENCES `mydb`.`building` (`idbuilding`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `OriginaldFloor`
    FOREIGN KEY (`idfloor`)
    REFERENCES `mydb`.`floor` (`idfloor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`normalUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`normalUser` (
  `iduser` INT NOT NULL,
  `normalUIddevice` INT NOT NULL,
  `name` INT NOT NULL,
  `password` INT NOT NULL,
  `normalUDefaultSourceLocation` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`iduser`),
  INDEX `iddevice_idx` (`normalUIddevice` ASC),
  INDEX `defaultSourceLocation_idx` (`normalUDefaultSourceLocation` ASC),
  CONSTRAINT `normalUIddevice`
    FOREIGN KEY (`normalUIddevice`)
    REFERENCES `mydb`.`device` (`iddevice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `normalUDefaultSourceLocation`
    FOREIGN KEY (`normalUDefaultSourceLocation`)
    REFERENCES `mydb`.`location` (`idlocation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`adminUser`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`adminUser` (
  `idadminUser` INT NOT NULL,
  `name` INT NULL,
  `password` INT NULL,
  `role` VARCHAR(45) NULL,
  PRIMARY KEY (`idadminUser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
