/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfance;

import business.ProductCatalog;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Brickea
 */
public class BtnPanel extends javax.swing.JPanel {

    /**
     * Creates new form BtnPanel
     */
    private JPanel viewPanel;
    private ProductCatalog productCatalog;

    BtnPanel(JPanel viewPanel, ProductCatalog productCatalog) {
        initComponents();
        this.viewPanel = viewPanel;
        this.productCatalog = productCatalog;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageBtn = new javax.swing.JButton();
        createBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 242, 228));
        setPreferredSize(new java.awt.Dimension(900, 600));

        manageBtn.setBackground(new java.awt.Color(255, 103, 103));
        manageBtn.setText("Manage Product");
        manageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBtnActionPerformed(evt);
            }
        });

        createBtn.setBackground(new java.awt.Color(255, 103, 103));
        createBtn.setText("Create Product");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(manageBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(693, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(manageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(392, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        CreatePanel createPanel = new CreatePanel(this.viewPanel,this.productCatalog);
        this.viewPanel.add("createPanel",createPanel);
        CardLayout layout = (CardLayout)this.viewPanel.getLayout();
        layout.next(this.viewPanel);
    }//GEN-LAST:event_createBtnActionPerformed

    private void manageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBtnActionPerformed
        // TODO add your handling code here:
        ManagePanel managePanel = new ManagePanel(this.viewPanel,this.productCatalog);
        this.viewPanel.add("managePanel",managePanel);
        CardLayout layout = (CardLayout)this.viewPanel.getLayout();
        layout.next(this.viewPanel);
    }//GEN-LAST:event_manageBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JButton manageBtn;
    // End of variables declaration//GEN-END:variables
}
